USE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE PRODUCTS;
CREATE OR REPLACE SCHEMA PRODUCTS.CUSTOMERS;

CREATE OR REPLACE TABLE PRODUCTS.CUSTOMERS.COMMISSIONS (
	COMPANY_NAME VARCHAR(100) NOT NULL,
	PROGRAM_CODE VARCHAR(50) NOT NULL,
	PRODUCT_CODE VARCHAR(50) NOT NULL,
	COMMISSION_AMOUNT NUMBER(4,2) NOT NULL,
	IS_ACTIVE BOOLEAN,
	UPDATED_LAST TIMESTAMP_NTZ(9),
	USERNAME VARCHAR(50)
);
