insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO123', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Silver Lining Inc.', 'PROJKL', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO123', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO123', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO789', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO456', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PROJKL', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO123', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO456', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PROJKL', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO456', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', '7PROVWX', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO456', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Silver Lining Inc.', 'PRO789', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PROGHI', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO123', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRO456', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO123', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', '7PROVWX', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO789', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PROGHI', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PROJKL', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO789', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO456', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PROGHI', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRODEF', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', '7PROVWX', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRODEF', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO123', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', '7PROVWX', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', '7PROVWX', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', '7PROVWX', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO456', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRO123', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', '7PROVWX', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRO123', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO789', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRODEF', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO123', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO456', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO123', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO123', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Silver Lining Inc.', 'PRO123', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRODEF', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Silver Lining Inc.', 'PRO456', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO123', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PROGHI', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO789', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO456', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PROJKL', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PROJKL', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', '7PROVWX', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRODEF', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PROJKL', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRODEF', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PROGHI', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRODEF', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PROGHI', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO456', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PROGHI', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRODEF', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PROJKL', 'MNO345');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO456', 'BCD890');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO123', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRODEF', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO456', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO789', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO123', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', '7PROVWX', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PROJKL', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO456', 'GHI789');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO456', 'JKL012');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO456', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO456', 'DG323');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PROGHI', 'YZA567');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO456', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO123', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO789', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', 'PRO123', 'VWX234');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO789', 'STU901');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO456', 'DEF456');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Widget Industries', '7PROVWX', 'PQR678');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PROJKL', 'DG323');