insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Acme Corporation', 'PRO123', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PROVWX', 'PROD46');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO457 PRO33I', 'PROD31 PROD86');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'PROD08');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO123', 'PROD00');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PROVWX', 'PROD00');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRO456', 'PROD39');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Starlight Solutions', 'PRO123', 'PROD46');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'PROD08');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Crimson Corporation', 'PRO123', 'PROD56');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO789', 'PROD46');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Ocean Blue Company', 'PRO456', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO123', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO456', 'PROD31 PROD86');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO456', 'PROD00');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Silver Lining Inc.', 'PRO123', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO34L', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO123', 'PROD39');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Sunshine Enterprises', 'PRO123', 'PROD31 PROD86');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO123', 'PROD39');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PROVWX', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Rainbow Co.', 'PRO123', 'PROD63');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Emerald Enterprises', 'PRO456', 'PROD31 PROD86');
insert into PRODUCTS.CUSTOMERS.MAPPING (company_name, program_code, product_code) values ('Golden Gate Group', 'PRO456', 'PROD32');